import puppeteer from 'puppeteer-core';
import http from 'http';
import fs from 'fs';
import path from 'path';
const MIME={'.html':'text/html','.js':'text/javascript','.glb':'model/gltf-binary','.bin':'application/octet-stream','.hdr':'image/vnd.radiance-hdr','.png':'image/png'};
const srv=http.createServer((q,r)=>{let p=q.url.split('?')[0];if(p==='/')p='/index.html';fs.readFile('/home/lex/chargebay'+p,(e,d)=>{if(e){r.writeHead(404);r.end();return;}r.writeHead(200,{'Content-Type':MIME[path.extname(p)]||'application/octet-stream'});r.end(d);});});
await new Promise(r=>srv.listen(8173,r));
const b=await puppeteer.launch({executablePath:'/usr/bin/chromium',args:['--no-sandbox','--use-gl=angle','--use-angle=vulkan','--enable-unsafe-swiftshader','--disable-dev-shm-usage'],defaultViewport:{width:1280,height:800}});
const pg=await b.newPage();
const errs=[]; pg.on('pageerror',e=>errs.push(e.message.slice(0,140)));
await pg.evaluateOnNewDocument(()=>{ localStorage.setItem('chargebay_coached_v1','1'); localStorage.removeItem('chargebay_save_v1'); });
await pg.goto('http://127.0.0.1:8173/',{waitUntil:'load',timeout:120000});
await pg.waitForFunction('window.__GAME&&window.__GAME.ready()',{timeout:180000});
await pg.evaluate("document.getElementById('start').style.display='none';");
await new Promise(r=>setTimeout(r,6000));
const info=await pg.evaluate("window.__GAME.q ? {props: (window.__GAME.propCount?window.__GAME.propCount():'n/a')} : {}");
await pg.evaluate("window.__GAME.lookAt(-8.6,0.55,-7.0, 3.2)");
await new Promise(r=>setTimeout(r,2500));
await pg.screenshot({path:'/home/lex/chargebay/progress/artifacts/scenery_bench.png'});
await pg.evaluate("window.__GAME.lookAt(0,1.5,10.5, 9)");
await new Promise(r=>setTimeout(r,2000));
await pg.screenshot({path:'/home/lex/chargebay/progress/artifacts/scenery_trees.png'});
console.log('props:', JSON.stringify(info), 'ERRORS:', errs.length?[...new Set(errs)].slice(0,4).join(' | '):'none');
await b.close(); srv.close();
