import puppeteer from 'puppeteer-core';
import http from 'http';
import fs from 'fs';
import path from 'path';
const MIME={'.html':'text/html','.js':'text/javascript','.glb':'model/gltf-binary','.bin':'application/octet-stream','.hdr':'image/vnd.radiance-hdr','.png':'image/png'};
const srv=http.createServer((q,r)=>{let p=q.url.split('?')[0];if(p==='/')p='/index.html';fs.readFile('/home/lex/chargebay'+p,(e,d)=>{if(e){r.writeHead(404);r.end();return;}r.writeHead(200,{'Content-Type':MIME[path.extname(p)]||'application/octet-stream'});r.end(d);});});
await new Promise(r=>srv.listen(8165,r));
const b=await puppeteer.launch({executablePath:'/usr/bin/chromium',args:['--no-sandbox','--use-gl=angle','--use-angle=vulkan','--enable-unsafe-swiftshader','--disable-dev-shm-usage'],defaultViewport:{width:1280,height:720}});
const pg=await b.newPage();
pg.on('pageerror',e=>console.log('ERR:',e.message.slice(0,140)));
await pg.goto('http://127.0.0.1:8165/',{waitUntil:'load',timeout:120000});
await pg.waitForFunction('window.__GAME&&window.__GAME.ready()',{timeout:180000});
await pg.evaluate("document.getElementById('start').style.display='none'; window.__GAME.weather(1);");
console.log('forceSeg:', await pg.evaluate("window.__GAME.forceSeg ? window.__GAME.forceSeg(0,'sedan') : 'NOHOOK'"));
await new Promise(r=>setTimeout(r,3200));
const out=await pg.evaluate("window.__GAME.probeCar(0)");
console.log('sweeps:', await pg.evaluate("window.__GAME.sweepCount(0)"), 'arms:', await pg.evaluate("window.__GAME.wiperCount(0)"));
const hl=out.parts.HeadL; const gl=out.parts.Glass;
const cx=(gl.min[0]+gl.max[0])/2, cz=(gl.min[2]+gl.max[2])/2;
const hx=(hl.min[0]+hl.max[0])/2, hz=(hl.min[2]+hl.max[2])/2;
console.log('glassC', cx.toFixed(2), cz.toFixed(2), 'headC', hx.toFixed(2), hz.toFixed(2));
// camera beyond headlights (that IS the front), near glass
const dx=hx-cx, dz=hz-cz; const L=Math.hypot(dx,dz);
const camx=cx+dx/L*2.6, camz=cz+dz/L*2.6;
await pg.evaluate("a=>{window.__GAME.pose(a.x, 1.0, a.z, 0, 0); window.__GAME.lookAt(a.gx, 0.8, a.gz, 2.7);}", {x:camx, z:camz, gx:cx, gz:cz});
await new Promise(r=>setTimeout(r,2200));
await pg.screenshot({path:'progress/artifacts/wiper_sedan.png'});
console.log('shot');
await b.close(); srv.close(); process.exit(0);