import puppeteer from 'puppeteer-core';
import http from 'http';
import fs from 'fs';
import path from 'path';
const MIME={'.html':'text/html','.js':'text/javascript','.glb':'model/gltf-binary','.bin':'application/octet-stream','.hdr':'image/vnd.radiance-hdr','.png':'image/png'};
const srv=http.createServer((q,r)=>{let p=q.url.split('?')[0];if(p==='/')p='/index.html';fs.readFile('/home/lex/chargebay'+p,(e,d)=>{if(e){r.writeHead(404);r.end('404 '+p);return;}r.writeHead(200,{'Content-Type':MIME[path.extname(p)]||'application/octet-stream'});r.end(d);});});
await new Promise(r=>srv.listen(8177,r));
const b=await puppeteer.launch({executablePath:'/usr/bin/chromium',args:['--no-sandbox','--use-gl=angle','--use-angle=vulkan','--enable-unsafe-swiftshader','--disable-dev-shm-usage'],defaultViewport:{width:640,height:400}});
const pg=await b.newPage();
const errs=[];
pg.on('pageerror',e=>errs.push('PAGEERR '+e.message.slice(0,200)));
pg.on('console',m=>{ if(m.type()==='error') errs.push('CONSOLE '+m.text().slice(0,200)); });
pg.on('requestfailed',r=>errs.push('REQFAIL '+r.url().split('/').slice(-2).join('/')+' '+(r.failure()||{}).errorText));
await pg.goto('http://127.0.0.1:8177/',{waitUntil:'load',timeout:60000});
await new Promise(r=>setTimeout(r,15000));
const st=await pg.evaluate("window.__GAME? window.__GAME.bays().map(b=>window.__GAME.bayState(b.i||0).state): 'no __GAME'").catch(e=>'EVAL '+e.message.slice(0,80));
console.log('states:', JSON.stringify(st));
console.log('ERRORS:\n'+[...new Set(errs)].slice(0,8).join('\n'));
await b.close(); srv.close();
