import puppeteer from 'puppeteer-core';
import http from 'http';
import fs from 'fs';
import path from 'path';
const MIME={'.html':'text/html','.js':'text/javascript','.glb':'model/gltf-binary','.bin':'application/octet-stream','.hdr':'image/vnd.radiance-hdr','.png':'image/png'};
const srv=http.createServer((q,r)=>{let p=q.url.split('?')[0]; if(p==='/')p='/index.html'; fs.readFile('/home/lex/chargebay'+p,(e,d)=>{if(e){r.writeHead(404);r.end();return;} r.writeHead(200,{'Content-Type':MIME[path.extname(p)]||'application/octet-stream'}); r.end(d);});});
await new Promise(r=>srv.listen(8149,r));
const b=await puppeteer.launch({executablePath:'/usr/bin/chromium',args:['--no-sandbox','--use-gl=angle','--use-angle=vulkan','--enable-unsafe-swiftshader','--disable-dev-shm-usage'],defaultViewport:{width:800,height:600}});
const pg=await b.newPage(); const errs=[];
pg.on('pageerror',e=>errs.push(e.message.slice(0,160)));
await pg.goto('http://127.0.0.1:8149/',{waitUntil:'load',timeout:120000});
await pg.waitForFunction('window.__GAME&&window.__GAME.ready()',{timeout:180000});
const S=e=>pg.evaluate(e);
await S("document.getElementById('start').style.display='none';");
const info=await S(`(()=>{const b=window.__GAME.bays[0];return 'hook';})()`);
// use existing carPos + add inline probe via __GAME internals: find glass & headlight world bboxes via traverse on bays[0].car (need raw bay access — bays hook is fn)
const out=await S(`(()=>{const g=window.__GAME; if(!g.probeCar) return 'noprobe'; return g.probeCar(0);})()`);
console.log('probeCar:', JSON.stringify(out));
console.log('ERRORS:', errs.length?errs.slice(0,2).join('|'):'none');
await b.close(); srv.close(); process.exit(0);
