import puppeteer from 'puppeteer-core';
import http from 'http';
import fs from 'fs';
import path from 'path';
const MIME={'.html':'text/html','.js':'text/javascript','.glb':'model/gltf-binary','.bin':'application/octet-stream','.hdr':'image/vnd.radiance-hdr','.png':'image/png'};
const srv=http.createServer((q,r)=>{let p=q.url.split('?')[0];if(p==='/')p='/index.html';fs.readFile('/home/lex/chargebay'+p,(e,d)=>{if(e){r.writeHead(404);r.end();return;}r.writeHead(200,{'Content-Type':MIME[path.extname(p)]||'application/octet-stream'});r.end(d);});});
await new Promise(r=>srv.listen(8163,r));
const b=await puppeteer.launch({executablePath:'/usr/bin/chromium',args:['--no-sandbox','--use-gl=angle','--use-angle=vulkan','--enable-unsafe-swiftshader','--disable-dev-shm-usage'],defaultViewport:{width:800,height:600}});
const pg=await b.newPage();
pg.on('pageerror',e=>console.log('ERR:',e.message.slice(0,140)));
await pg.goto('http://127.0.0.1:8163/',{waitUntil:'load',timeout:120000});
await pg.waitForFunction('window.__GAME&&window.__GAME.ready()',{timeout:180000});
await pg.evaluate("document.getElementById('start').style.display='none';");
await pg.evaluate("window.__GAME.clearBay(0); window.__GAME.forceArr(0);");
await new Promise(r=>setTimeout(r,2500));
console.log(await pg.evaluate("(()=>{const b=window.__GAME.bays()[0]; if(!b||!b.car) return 'nocar'; const names=[]; b.car.traverse(o=>{ names.push(o.name); }); return 'nodes='+names.length+' | '+names.slice(0,60).join(',');})()"));
await b.close(); srv.close(); process.exit(0);