import puppeteer from 'puppeteer-core';
import http from 'http';
import fs from 'fs';
import path from 'path';
const MIME={'.html':'text/html','.js':'text/javascript','.glb':'model/gltf-binary','.bin':'application/octet-stream','.hdr':'image/vnd.radiance-hdr','.png':'image/png'};
const srv=http.createServer((q,r)=>{let p=q.url.split('?')[0];if(p==='/')p='/index.html';fs.readFile('/home/lex/chargebay'+p,(e,d)=>{if(e){r.writeHead(404);r.end();return;}r.writeHead(200,{'Content-Type':MIME[path.extname(p)]||'application/octet-stream'});r.end(d);});});
await new Promise(r=>srv.listen(8162,r));
const b=await puppeteer.launch({executablePath:'/usr/bin/chromium',args:['--no-sandbox','--use-gl=angle','--use-angle=vulkan','--enable-unsafe-swiftshader','--disable-dev-shm-usage'],defaultViewport:{width:1280,height:720}});
const pg=await b.newPage();
pg.on('pageerror',e=>console.log('ERR:',e.message.slice(0,140)));
await pg.goto('http://127.0.0.1:8162/',{waitUntil:'load',timeout:120000});
await pg.waitForFunction('window.__GAME&&window.__GAME.ready()',{timeout:180000});
await pg.evaluate("document.getElementById('start').style.display='none'; window.__GAME.weather(1); window.__GAME.clearBay(0); window.__GAME.forceArr(0);");
await new Promise(r=>setTimeout(r,1600));
console.log('wiperCount:', await pg.evaluate("window.__GAME.wiperCount(0)"), 'sweeps:', await pg.evaluate("window.__GAME.sweepCount(0)"));
const armPos = "(()=>{const car=window.__GAME.bays()[0].car; if(!car) return null; car.updateMatrixWorld(true); const out=[]; car.traverse(o=>{ if(/^WiperArm/.test(o.name||'')){ const m=o.matrixWorld; out.push([+m.elements[12].toFixed(2),+m.elements[13].toFixed(2),+m.elements[14].toFixed(2)]); } }); return out;})()";
const s1=await pg.evaluate(armPos);
await new Promise(r=>setTimeout(r,1400));
const s2=await pg.evaluate(armPos);
console.log('arm tips t1:', JSON.stringify(s1));
console.log('arm tips t2:', JSON.stringify(s2));
const p=await pg.evaluate("window.__GAME.carPos(0)");
await pg.evaluate("(p)=>{const g=window.__GAME;g.pose(p.x, 1.1, p.z+5.5, 0, 0); g.lookAt(p.x, 0.9, p.z, 5.6);}", p);
await new Promise(r=>setTimeout(r,2200));
await pg.screenshot({path:'progress/artifacts/wiper_final.png'});
console.log('shot');
await b.close(); srv.close(); process.exit(0);